# Generated by Django 3.0.6 on 2020-10-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='Movie',
        ),
    ]
