# Generated by Django 3.0.6 on 2020-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20201011_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('adventure', 'ADVENTURE'), ('fantasy', 'FANTASY'), ('science_fiction', 'SCIENCE FICTION'), ('action', 'ACTION'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=40),
        ),
    ]
