# Generated by Django 3.1.3 on 2020-11-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0008_myrecommender'),
    ]

    operations = [
        migrations.AddField(
            model_name='myrecommender',
            name='liked_movie',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
