# Generated by Django 3.1.3 on 2020-11-07 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0010_movie_box_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year_of_release',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
