# Generated by Django 3.0.6 on 2020-11-09 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='movie',
        ),
    ]
